
name: Todo App CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: [self-hosted, linux, x64]
    steps:
        
      - name: Check AWS credentials
        run: |
          aws sts get-caller-identity
          aws configure list
